### ISSUE TITLE
How do i get this to work?

### ISSUE THREAD

**Issue by jsuhhome** [craigahobbs/unittest-parallel#1]
tried `unittest-parallel -j 3`

with 

     class TestA(unittest.TestCase):
       def setUp(self):
        pass

    def test_A(self):
        for i in range(10):
            print('A' + str(i) + ': ' + str(datetime.datetime.now()))
            time.sleep(1)

    def test_B(self):
        for i in range(10):
            print('B' + str(i) + ': ' + str(datetime.datetime.now()))
            time.sleep(1)

    def test_C(self):
        for i in range(10):
            print('C' + str(i) + ': ' + str(datetime.datetime.now()))
            time.sleep(1)

    def tearDown(self):
        pass

   if __name__ == '__main__':
      unittest.main()

but it went sequentially

**Comment by craigahobbs** [comment]
unittest-parallel parallelizes at the test suite level (your class
definition).  To get your tests to run in parallel above you'd need to put
them each in their own class.  IMO unittest-parallel is best used for
projects with 100's or 1000's of unit tests.  For anything less I'd
recommend using the built-in python unit test runner (python -m unittest).

Craig
