### ISSUE TITLE
Feature -f / --failfast option

### ISSUE THREAD

**Issue by mwchambers** [craigahobbs/unittest-parallel#10]
Would it be possible to add an option which stops the test run on the first error or failure?

Like: https://docs.python.org/3/library/unittest.html#cmdoption-unittest-f

It looks like failfast=True could be passed to unittest.TextTestRunner

https://docs.python.org/3/library/unittest.html#unittest.TextTestRunner

Though I imagine there is other work that would need to be done to shutdown the multiprocessing.Pool so other tests do not continue to run?

**Comment by craigahobbs** [comment]
Yes, that should be straightforward to add. I'll take a look.

**Comment by craigahobbs** [comment]
Released unittest-parallel 1.4.0 with "--failfast" argument. Let me know if it doesn't work as expected.

**Comment by mwchambers** [comment]
@craigahobbs Thank you for spending your time on this, it is much appreciated!
