### ISSUE TITLE
Some frameworks deadlock when executed with unittest-parallel

### ISSUE THREAD

**Issue by stewartmiles** [craigahobbs/unittest-parallel#11]
unittest-parallel is currently using the default process spawning behavior of the multiprocessing module (i.e `fork` on Linux) which can lead to subprocesses hanging. For a detailed explanation see https://britishgeologicalsurvey.github.io/science/python-forking-vs-spawn/

**Comment by craigahobbs** [comment]
Published unittest-parallel 1.5.0

https://pypi.org/project/unittest-parallel/1.5.0/

**Comment by stewartmiles** [comment]
Woo thanks @craigahobbs !
