### ISSUE TITLE
Parameterize the module I want to use to run tests

### ISSUE THREAD

**Issue by felipearcaro** [craigahobbs/unittest-parallel#19]
I've been using your package and it works great, thank you for building it. 

When I run `python -m unittest`, it executes the `unittest` module as a script - something like `python unittest.py`, which gives me some flexibility. For example, when I run Python unit tests inside of TeamCity, I can run `python -m teamcity.unittestpy` instead to use TeamCity's Python package (essentially a wrapper around `unittest` module) - that discovers and runs tests, and reports the results in a format that TeamCity can understand.

Do you think that could be added as a parameter, something like `unittest-parallel -m teamcity.unittestpy`?
By quickly looking at your code and [teamcity-messages's documentation](https://github.com/JetBrains/teamcity-messages?tab=readme-ov-file#usage), I believe that, in the scenario I described above, [this line](https://github.com/craigahobbs/unittest-parallel/blob/72cf639c56984de882e75566af95fee084774dd5/src/unittest_parallel/main.py#L277) would run `TeamcityTestRunner()` instead.

I would be more than happy to work on it and put up a PR, let me know.

Note: This is probably an enhancement and not an issue.

**Comment by craigahobbs** [comment]
Sounds similar to #16.

**Comment by felipearcaro** [comment]
Oh right - I'll put up a PR for you to review. Thanks!

**Comment by craigahobbs** [comment]
Working in "feature/custom-runner":

https://github.com/craigahobbs/unittest-parallel/tree/feature/custom-runner

**Comment by craigahobbs** [comment]
Duplicate of #16
