### ISSUE TITLE
How do I use it on my project?

### ISSUE THREAD

**Issue by alexandrebarbaruiva** [craigahobbs/unittest-parallel#2]
How do I use `unittest-parallel` in my project?

When I run 
```
unittest-parallel tests.py
```
I get the following error
```
unittest-parallel: error: unrecognized arguments: tests.py
```

**Comment by craigahobbs** [comment]
unittest-parallel is implicitly "discover" based on the presumption that you'll have lots of unit tests (and hence the need for a parallel unit test runner). Is your case different?

So, the way to run it is:

    unittest-parallel

or perhaps more exactly:

    unittest-parallel -p test.py

**Comment by craigahobbs** [comment]
Updated README with usage examples.
