### ISSUE TITLE
Error - raise ImportError('Start directory is not importable: %r' % start_dir)

### ISSUE THREAD

**Issue by unfor19** [craigahobbs/unittest-parallel#4]
Hi, thank you for this tool
Just pointing out that I had to add `__init__.py` to my `tests` dir for this tool to work

**Comment by craigahobbs** [comment]
This is a design decision of Python's unittest discovery mechanism.

https://bugs.python.org/issue26481

**Comment by unfor19** [comment]
@craigahobbs I understand that, just thought it would be good if you add it to the `README.md` so other folks would easily use this tool. Up to you my friend
